# Specify the base image
FROM python:3.9

# Install OS dependencies
# RUN apt-get update

# Set the working directory inside the container
WORKDIR /

#ENV PYTHONPATH "${PYTHONPATH}:/src"

COPY requirements.txt requirements.txt
COPY . .

RUN pip3 install -r requirements.txt

# Expose the necessary port(s)
EXPOSE 10101

ENTRYPOINT [ "wave", "run", "src.app.app.py"]
